package megalodonte.contracts;

public enum Capability {
    TEXT, BUTTON, CONTAINER, REACTIVE_STATE, THEME_TOKENS, SPACING,
    INPUT, CHECKBOX, SELECT, DATE_PICKER, IMAGE, PROGRESS,
    ROW, COLUMN, STACK, SCROLL, CARD, GRID, TABLE, MENU, MODAL,
    CONDITIONAL_RENDERING, LIST_RENDERING, ROUTING, ASYNC_SCOPE,
    CUSTOM_FONTS, DESKTOP_WINDOWS, JAVAFX_NODE, JAVAFX_CSS, KEYBOARD_SHORTCUTS
}
